services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        working_dir: /app
        ports:
            - "10101:10101"
        expose:
            - "10101"
        env_file:
            - ".env"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        working_dir: /usr/share/nginx/html
        ports:
            - "10100:80"
        expose:
            - "10100"
        depends_on:
            - backend
